### ISSUE TITLE
Stats? 1.1.12 Windows 10

### ISSUE THREAD

**Issue by konkersgg** [abueide/harry-plotter#85] opened 2021-06-04 03:35 UTC
Ok, wth is this?

![image](https://user-images.githubusercontent.com/4704759/120741894-56965f80-c4cc-11eb-8d0a-96c08949c930.png)

I don't think that those are the kind of stats I'd like to know. I mean, is this total plots made with your app or is there something wrong?

That number won't stop growing. By the time I'm wrinting this its already on 50k and still loading... it's also sucking up 20% of my CPU without doing anything other than loading `Total Plots Completed`.

![image](https://user-images.githubusercontent.com/4704759/120742103-b2f97f00-c4cc-11eb-8f4a-94667263bc9e.png)

**Comment by abueide** [comment] 2021-06-04 03:45
yeah no thats definitely a bug i'll look into it

**Comment by konkersgg** [comment] 2021-06-04 03:50
> yeah no thats definitely a bug i'll look into it. if you have any insights about your setup that might make this happen, let me know, because I've not been able to reproduce it. I'd recommend to try clearing your logs folder in ~/.harryplotter/logs
> 
> also are you on 1.1.12 or 1.1.12-RC?

1.1.12

**Comment by abueide** [comment] 2021-06-04 18:00
I can't reproduce. Please let me know if this is still happening & if you'd be willing to do a discord call debugging session so I can fix it.

Thanks,
Andrew

**Comment by ti6462** [comment] 2021-06-04 18:50
Same Issue, windows 10 running 1.1.13.  I cleared the log files and it seems to have resolved the problem.

[image](https://user-images.githubusercontent.com/12099667/120849415-14106980-c544-11eb-9387-9d0b22a6416b.png)

**Comment by konkersgg** [comment] 2021-06-04 23:40
> I can't reproduce. Please let me know if this is still happening & if you'd be willing to do a discord call debugging session so I can fix it.
> 
> Thanks,
> Andrew

Sure we can do that if deleting logs doesn't work. I have a bunch of logs from Swar and PlotNG. Maybe that's the issue? I'll try @ti6462's approach and let you know if it fixes it.



> Same Issue, windows 10 running 1.1.13. I cleared the log files and it seems to have resolved the problem.
> 
> [image](https://user-images.githubusercontent.com/12099667/120849415-14106980-c544-11eb-9387-9d0b22a6416b.png)

135k? Really?

**Comment by konkersgg** [comment] 2021-06-05 00:25
Where does Harry Plotter stores logs btw? I removed all of the lots in my plotter folder but Harry still tells me I have created one plot.

**Comment by abueide** [comment] 2021-06-05 00:28
it stores in ~/.harryplotter/logs/finished

**Comment by abueide** [comment] 2021-06-05 00:46
I think i found the problem, will try adding the fix to the next release. I think it happens when there is a file inside of the plot logs where it can't parse the plot id, causing it to infinitely add that file as an empty job result.

**Comment by konkersgg** [comment] 2021-06-05 01:29
> it stores in ~/.harryplotter/logs/finished

There is no such folder here!

**Comment by abueide** [comment] 2021-06-05 01:43
@konkersgg sorry its ~/.harryplotter/plotlogs/finished

**Comment by konkersgg** [comment] 2021-06-05 03:04
> @konkersgg sorry its ~/.harryplotter/plotlogs/finished

Deleting all the logs fixed it indeed.

**Comment by abueide** [comment] 2021-06-05 05:39
fixed in 1.1.14

**Closed by abueide** 2021-06-05 05:39 UTC
